set number
set cursorline
set showmatch

set incsearch
set nohlsearch
set ignorecase
set smartcase
set shortmess-=S
set wildmenu wildmode=full
set wildignorecase
set foldmethod=indent

if has("patch-8.1.0360")
  set diffopt+=internal,algorithm:histogram,indent-heuristic
endif

" ---- indent ----
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent
set expandtab
" 改行時自動コメントアウトしない
autocmd FileType * setlocal formatoptions-=ro

" ---- status line ----
set laststatus=2
set statusline=%<%F\ %m%r%h
set statusline+=%{'['.(&fenc!=''?&fenc:&enc).']['.&fileformat.']'}
set statusline+=%=[%v]\ %l/%L\ %P
set showcmd

set mouse=a
set backspace=indent,eol,start
set whichwrap=b,s
set scrolloff=4

" ---- encode ----
if &fenc !=# 'utf-8'
  set enc=utf-8
  set fenc=utf-8
  set fencs=ucs-bom,utf-8,iso-2022-jp-3,iso-2022-jp,cp932,sjis,euc-jp
endif
" 全角記号の文字幅
set ambiwidth=double

" ---- cursor ----
if has("vim_starting")
  let &t_SI .= "\e[5 q"  " bar cursor shape
  let &t_EI .= "\e[1 q"  " block cursor shape
endif

runtime! config/*.vim
