set number
set cursorline
set showmatch

set incsearch
set nohlsearch
set ignorecase
set smartcase
set shortmess-=S
set wildmenu wildmode=full
set wildignorecase
set foldmethod=indent

if has('patch-8.1.0360')
  set diffopt+=internal,algorithm:histogram,indent-heuristic
endif

" ---- status line ----
set laststatus=2
set statusline=%<%F\ %m%r%h
set statusline+=%{'['.(&fenc!=''?&fenc:&enc).']['.&fileformat.']'}
set statusline+=%=[%v]\ %l/%L\ %P
set showcmd

set mouse=a
set backspace=indent,eol,start
set whichwrap=b,s
set scrolloff=4

" ---- encode ----
if &fenc !=# 'utf-8'
  set enc=utf-8
  set fenc=utf-8
  set fencs=ucs-bom,utf-8,iso-2022-jp-3,iso-2022-jp,cp932,sjis,euc-jp
endif

" ---- cursor ----
if has('vim_starting')
  let &t_SI .= "\e[5 q"  " bar cursor shape
  let &t_EI .= "\e[1 q"  " block cursor shape
endif

" ---- XDG ----
if !has('nvim')
  set viminfofile=$XDG_CACHE_HOME/vim/viminfo
endif

filetype off
runtime! config/plugin.vim
runtime! config/color.vim
runtime! config/indent.vim
runtime! config/mapping.vim
runtime! config/optional.vim
